version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.0.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: nebulab/pa11yci
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          ssh-fingerprints: aa:fa:55:39:58:1c:10:09:63:78:b3:6e:7b:f9:bc:27
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: aa:fa:55:39:58:1c:10:09:63:78:b3:6e:7b:f9:bc:27
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: nebulab/pa11yci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          orb-name: nebulab/pa11yci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          orb-name: nebulab/pa11yci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
